sonata_media:
    class:
        media:              App\Application\Sonata\MediaBundle\Entity\Media
        gallery:            App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            #Дефолтные примеры
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        user:
            providers:
                - sonata.media.provider.image

            formats:
                preview: { width: 270 , quality: 95}
                mini: { width: 85 , quality: 95}
                desktop: { width: 540 , quality: 95}
                mobile: { width: 220 , quality: 95}
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  '%kernel.root_dir%/../public/uploads/media'
            create:     false
    #Начало имедж провайдеров
    providers:
        image:
            service:    sonata.media.provider.image
            resizer:    sonata.media.resizer.simple # sonata.media.resizer.square
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['jpg', 'png', 'gif', 'jpeg'] # Optional
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif'] # Optional


