version: '3.7'

services:
  db:
    image: mysql:5.7.28
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sandbox
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - backend

  php:
    build: ./docker/images/php
    volumes:
      - ./symf-proj:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
    networks:
      - backend

  nginx:
    build: ./docker/images/nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
    networks:
      - backend

networks:
  backend:
    driver: "bridge"