version: '3.7'

services:
  db:
    container_name: ${CONTAINER_PREFIX}_db
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend

  phpmyadmin:
    container_name: ${CONTAINER_PREFIX}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  php:
    container_name: ${CONTAINER_PREFIX}_php
    build: ./docker/images/php
    volumes:
      - ./symf-proj:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
    networks:
      - backend

  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    build: ./docker/images/nginx
    ports:
      - "8084:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./symf-proj:/var/www/symfony
    networks:
      - backend

networks:
  backend:
    driver: "bridge"