monolog:
    handlers:
        main:
            type: rotating_file
            path: "/var/www/symfony/log/default.log"
            level: info
            channels: ["default"]
        registration:
            type: rotating_file
            path: "/var/www/symfony/log/registration.log"
            level: info
            channels: ["registration"]
        mailing:
            type: rotating_file
            path: "/var/www/symfony/log/mail.log"
            level: info
            channels: ["mailer"]