name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Change directory
      run: cd symf-proj/

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate composer.json and composer.lock
      run: composer validate

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
